### ISSUE TITLE
RSS nie działa

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#1]
# Kroki reprodukcji
1. wejść na stronę główną
1. kliknąć w link _RSS_ na samym dole

# Oczekiwany efekt
Otwarcie strony z feedem RSS lub brak takiego linka (jeśli funkcja nie działa)

# Osiągnięty rezultalt
Po kliknięciu w RSS na dole strony jestem przekierowany na https://spaczek.dev/feed, a następnie na https://spaczek.dev/404.

Przeglądarka: Brave, Firefox, wyłączony adblock

**Comment by pspaczek** [comment]
usunięto, do przywrócenia po migracji na zhp.pl
