### ISSUE TITLE
Link do starej strony w kontakcie

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#10]
1. wejdź na https://spaczek.dev/kontakt
1. kliknij na link na dole strony (_Przejdź do serwisu dla mediów_)

# oczekiwany rezultat
przechodzę do zakładki _Dla mediów_

# otrzymany rezultat
Przechodzę na starą stronę https://zhp.pl/media/. Ta strona jeszcze działa, ale https://spaczek.dev/media/ daje 404, więc zakładam, że po przepięciu domen to padnie

**Comment by pspaczek** [comment]
## rozwiązanie 
konieczne jest zamienianie w tekście z WordPress tagu <a> na <z-link> przez automat przed wyrenderowaniem strony

**Comment by pspaczek** [comment]
## rozwiązano
regex parsujący link na komponent vue
