### ISSUE TITLE
Odkryj ZHP znajduje się pod komponentami na stronie aktualności

### ISSUE THREAD

**Issue by vasiliev123** [pspaczek/nowa-zhp#11]
Po kliknięciu bądź najechaniu na Odrkyj ZHP rozwijane menu znajduje się pod buttonami Wybierz datę/Wybierz kategorię'

Chrome oraz Firefox w najnowszej wersji:

![obraz](https://user-images.githubusercontent.com/5650567/99952675-4ca6dd80-2d80-11eb-9344-2aa15ed52f65.png)

**Comment by pspaczek** [comment]
naprawiono
![Zrzut ekranu 2020-11-25 o 08 23 39](https://user-images.githubusercontent.com/12138170/100195394-9403aa00-2ef7-11eb-8aba-1f50775597de.png)
