### ISSUE TITLE
Font w innych wersjach językowych źle obsługuje znaki diakrytyczne

### ISSUE THREAD

**Issue by szczot3k** [pspaczek/nowa-zhp#12]
![image](https://user-images.githubusercontent.com/23485507/99961578-f4c3a300-2d8e-11eb-82d2-17888bc8e2a0.png)

Font w "cytacie" nie ogarnia "ogonków" w innych wersjach językowych niż polskiej. Błąd występuje we francuskiej i hiszpańskiej wersji.

**Comment by pspaczek** [comment]
<img width="1429" alt="Zrzut ekranu 2020-11-23 o 15 41 29" src="https://user-images.githubusercontent.com/12138170/99975345-648f5900-2da2-11eb-864a-0bab7fc9892f.png">

naprawione, dzięki
