### ISSUE TITLE
Dla mediów: Wygasłe link do sharepointa

### ISSUE THREAD

**Issue by szczot3k** [pspaczek/nowa-zhp#15]
Jak w temacie. Może warto byłoby przemyśleć ten temat, żebyście nie musieli co jakiś czas tego odświeżać?

**Comment by marti-xd** [comment]
Na ten moment poprawione -zapytaj Jana jak to można zrobić, żeby link nie działał tylko 60 dni ;)

**Comment by janekk97** [comment]
Dla linków poza organizację się nie da, ustaw sobie przypomnienie xd

**Comment by szczot3k** [comment]
Pisząc "może warto przemyśleć temat" myślałem raczej nad trzymaniem identyfikatora i logo poza sharepointem, ale możecie też odświeżać co 60 dni.

**Comment by szczot3k** [comment]
Zamykam, sam problem rozwiązany
