### ISSUE TITLE
strona RODO nieintuicyjna

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#16]
na początku myślałem że to błąd że na stronie RODO w ZHP jest przycisk RODO w ZHP który przenosi do strony RODO w ZHP ale to jednak jest menu
może warto zrobić jedną stronę zamiast 2 tutaj?
![image](https://user-images.githubusercontent.com/36226444/99968881-02325a80-2d9a-11eb-9c62-c1728b9f119d.png)

Ponadto mylące jest że "Polityka prywatności" przenosi do RODO w ZHP, polityka powinna być wklejona jako tekst na stronę a nie jako plik do pobrania. Księga klauzul jest tu niepotrzebna moim zdaniem, można ją przenieść do intranetu.

**Comment by marti-xd** [comment]
1. Księga klauzul tu musi być - Kasia tak mówi a ja jej ufam
2. polityka prywatności będzie tak 
3. zmienię na jedną stronę całość - wpisałam na swoją listę

**Comment by janekk97** [comment]
2. tak czyli jak?

**Comment by marti-xd** [comment]
że na dole linkuje do strony RODO gdzie jest wszystko w tym polityka

**Comment by pspaczek** [comment]
Issue dotyczący contentu. Rozwiązany przez Wydziału Komunikacji i Promocji GK ZHP
