### ISSUE TITLE
menu na małych ekranach - brak odstępu, brak zawijania wierszy

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#17]
![image](https://user-images.githubusercontent.com/36226444/99969582-fb581780-2d9a-11eb-97da-70e3befe70c6.png)

**Comment by pspaczek** [comment]
## rozwiązanie
![Zrzut ekranu 2020-11-25 o 15 39 54](https://user-images.githubusercontent.com/12138170/100241874-79035b00-2f34-11eb-8558-3c4c733fafe2.png)
