### ISSUE TITLE
newsy na małych ekranach - ucięte słowa

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#18]
![image](https://user-images.githubusercontent.com/36226444/99969635-0f037e00-2d9b-11eb-9a0e-6296cfc9a69a.png)
może warto zmniejszyć też liczbę newsów w wierszu?

**Comment by pspaczek** [comment]
## rozwiązanie
![Zrzut ekranu 2020-11-25 o 15 14 47](https://user-images.githubusercontent.com/12138170/100238845-f62cd100-2f30-11eb-84f2-b36e86133e52.png)
