### ISSUE TITLE
tagi w wydarzeniach - ucięte, za duże odstępy

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#19]
![image](https://user-images.githubusercontent.com/36226444/99969888-5c7feb00-2d9b-11eb-8794-efdbda61d050.png)

**Comment by pspaczek** [comment]
## rozwiązano
![Zrzut ekranu 2020-11-25 o 16 22 20](https://user-images.githubusercontent.com/12138170/100247604-c8e52080-2f3a-11eb-9ecb-92e0f3775980.png)
