### ISSUE TITLE
Link Polityka Prywatności prowadzi do kontaktu

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#2]
# kroki
1. wejdź na stronę główną
1. kliknij na dole _Polityka prywatności_

# Oczekiwany rezultat
Przekieruje mnie na stronę https://spaczek.dev/rodo/rodo-w-zhp (lub bezpośrednio do polityki)

# otrzymany rezultalt
Otwiera się strona https://spaczek.dev/rodo/kontakt

**Comment by pspaczek** [comment]
przekierowanie na /rodo/rodo-w-zhp
