### ISSUE TITLE
menu nie odznacza się na tle strony, logo zhp na środku źle wygląda

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#20]
![image](https://user-images.githubusercontent.com/36226444/99969972-79b4b980-2d9b-11eb-98e9-82d23525c9d0.png)

**Comment by marti-xd** [comment]
A dla mnie dobrze wygląda- zostaje XD

**Comment by marti-xd** [comment]
appapaapapapapapapap

**Comment by janekk97** [comment]
wrrrrrrrrrrrrrrrrrrrrrrrr
to ma być strona dla wszystkich a nie dla Ciebie lol

**Comment by janekk97** [comment]
sama dobrze wyglądasz xd

**Comment by marti-xd** [comment]
No ja wiem, że ja dobrze wyglądam 👍 

Tak było zaprojektowane i tak zostanie ;) Ne dogodzimy wszystkim - sorki!

**Comment by pspaczek** [comment]
![Zrzut ekranu 2020-11-23 o 22 46 04](https://user-images.githubusercontent.com/12138170/100019027-b1dcec00-2ddd-11eb-8f5a-9fea5d971f29.png)

W projekcie po lewej stronie jest kontrolka, której jeszcze nie wdrażamy. W wdrożonej konfiguracji logotyp po środku rzeczywiście wygląda odrobinę jak "upośledzony".

Tak wyglądałby nagłówek w przypadku keidy logo trafiłoby do lewej.

![Zrzut ekranu 2020-11-23 o 22 49 40](https://user-images.githubusercontent.com/12138170/100019380-37f93280-2dde-11eb-93d4-ef2c6dfee241.png)

**Comment by marti-xd** [comment]
Ej moim zdaniem on wygląda spoko na środku!

**Comment by pspaczek** [comment]
K, nie dyskutuję, zamykam 👍
