### ISSUE TITLE
brak spójności w formatowaniu tekstu

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#22]
np. rzecznika jest pogrubiona, IODO nie, po nazwie funkcji IOD jest dwukropek, po rzeczniczce nie ma; w rzeczniczce mail jest pierwszy a w IODO pierwszy jest telefon
![image](https://user-images.githubusercontent.com/36226444/99970243-dadc8d00-2d9b-11eb-8a8c-3f2159544bf9.png)

**Comment by marti-xd** [comment]
done - nie wiem jak to tu zamknąć :D
