### ISSUE TITLE
Wyszukiwarka: puste wyszukiwania

### ISSUE THREAD

**Issue by szczot3k** [pspaczek/nowa-zhp#23]
Bez problemu można wyszukiwać nie podając co chcemy wyszukać, co prowadzi do popsutych treści.

![image](https://user-images.githubusercontent.com/23485507/100011491-1a25d080-2dd2-11eb-8db0-488c364dadfb.png)

**Comment by pspaczek** [comment]
## rozwiązanie
wdrożenie walidacji dla min 3 znaków

![search](https://user-images.githubusercontent.com/12138170/100058075-f5107c80-2e28-11eb-8c39-66ec5cc26cb2.gif)
