### ISSUE TITLE
Linki do konkretnej podstrony lub "hard refresh" zwracają Server Error

### ISSUE THREAD

**Issue by Frezzu** [pspaczek/nowa-zhp#26]
1. Wejdź bezpośrednio na link https://spaczek.dev/odkryj/statut-zhp/ (przeglądarka/karta incognitio pomaga)
2. LUB odśwież stronę przez "hard refresh" (Czyści cookies, Command + Shift + R na Macu na Chromie, na windowsie Ctrl + przycisk Refresh na toolbarze)
3. Wyświetla się strona z Server Error

Przglądarka: Chrome Version 86.0.4240.198 (Official Build) (x86_64)
Adblock: true
Brak błędów w konsoli

![Screenshot 2020-11-25 at 17 36 01](https://user-images.githubusercontent.com/12649303/100256251-ddc6b180-2f44-11eb-94c3-b7150c10fb7e.png)

**Comment by pspaczek** [comment]
#38 rozwiązane
