### ISSUE TITLE
Link organizatora wydarzenia nie działa

### ISSUE THREAD

**Issue by Frezzu** [pspaczek/nowa-zhp#28]
1. Wejdź na jakieś wydarzenie (np. https://spaczek.dev/wydarzenia/betlejemski-zlot-2021)
2. Kliknij link organizatora (box, prawa strona)
3. Otwiera się nowa strona z Server Error

Przglądarka: Chrome Version 86.0.4240.198 (Official Build) (x86_64)
Adblock: true
Brak błędów w konsoli

![Screenshot 2020-11-25 at 18 06 29](https://user-images.githubusercontent.com/12649303/100260121-57f93500-2f49-11eb-9ee9-3a0f56181fed.png)
![Screenshot 2020-11-25 at 18 06 38](https://user-images.githubusercontent.com/12649303/100260138-5a5b8f00-2f49-11eb-89b7-9cec3df25299.png)

Logi z konsoli
![Screenshot 2020-11-25 at 18 10 10](https://user-images.githubusercontent.com/12649303/100260255-7e1ed500-2f49-11eb-9cea-72dd42f2566e.png)

**Comment by pspaczek** [comment]
## rozwiązano 
w wydarzeniach należy podawać adres URL z `http://` lub `https://` za content odpowiada Wydział Komunikacji
