### ISSUE TITLE
ERROR  Request failed with status code 403

### ISSUE THREAD

**Issue by dkoryto** [pspaczek/nowa-zhp#29]
yarn run v1.22.5
$ cd packages/app && yarn start
$ nuxt start

   ╭──────────────────────────────────────────╮
   │                                          │
   │   Nuxt.js @ v2.14.7                      │
   │                                          │
   │   ▸ Environment: production              │
   │   ▸ Rendering:   server-side             │
   │   ▸ Target:      server                  │
   │                                          │
   │   Memory usage: 23.9 MB (RSS: 69.5 MB)   │
   │                                          │
   │   Listening: http://172.17.0.2:3000/     │
   │                                          │
   ╰──────────────────────────────────────────╯

 ERROR  Request failed with status code 403

  at createError (/usr/src/nuxt-app/node_modules/axios/lib/core/createError.js:16:15)
  at settle (/usr/src/nuxt-app/node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (/usr/src/nuxt-app/node_modules/axios/lib/adapters/http.js:244:11)
  at IncomingMessage.emit (events.js:327:22)
  at IncomingMessage.EventEmitter.emit (domain.js:486:12)
  at endReadableNT (_stream_readable.js:1327:12)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by pspaczek** [comment]
nie występuje

**Comment by dkoryto** [comment]
Potwierdzam występuje:  nowe.zhp.pl/

Attaching to nowa-zhp_web_1
web_1  | yarn run v1.22.5
web_1  | $ cd packages/app && yarn start
web_1  | $ nuxt start
web_1  | ✔ Sentry reporting is enabled (client side: enabled, server side: enabled)
web_1  | ℹ Listening on: http://172.18.0.2:3000/
web_1  | 
web_1  |  ERROR  Request failed with status code 403
web_1  | 
web_1  |   at createError (/usr/src/nuxt-app/node_modules/axios/lib/core/createError.js:16:15)
web_1  |   at settle (/usr/src/nuxt-app/node_modules/axios/lib/core/settle.js:17:12)
web_1  |   at IncomingMessage.handleStreamEnd (/usr/src/nuxt-app/node_modules/axios/lib/adapters/http.js:244:11)
web_1  |   at IncomingMessage.emit (events.js:327:22)
web_1  |   at IncomingMessage.EventEmitter.emit (domain.js:548:15)
web_1  |   at endReadableNT (_stream_readable.js:1327:12)
web_1  |   at processTicksAndRejections (internal/process/task_queues.js:80:21)
web_1  |
