### ISSUE TITLE
Odnośnik do BIPu prowadzi do błędu SSL

### ISSUE THREAD

**Issue by szczot3k** [pspaczek/nowa-zhp#3]
W stopce, po kliknięciu na odnośnik do BIPu dostajemy stronę z błędem SSL przez fakt, że href prowadzi do subdomeny WWW.bip.zhp.pl - którego nie łapie wildcard *.zhp.pl.

**Comment by qj0n** [comment]
Wystarczy, żeby link prowadził do https://bip.zhp.pl/

**Comment by pspaczek** [comment]
przekierowano na https://bip.zhp.pl/
