### ISSUE TITLE
[Propozycja] Sticky header + back to top przycisk

### ISSUE THREAD

**Issue by Frezzu** [pspaczek/nowa-zhp#30]
Proponuję dodanie popularnego na stronach "sticky header" wraz z przyciskiem "back to top"

**Comment by pspaczek** [comment]
#21 już jest, w temacie back to top, jeżeli sticky header to bez sensu jest back to top skoro nawigacja jest przyklejona IMO 

## rowziązane tymczasowo dla mobile 
<img width="356" alt="Zrzut ekranu 2020-11-26 o 10 05 16" src="https://user-images.githubusercontent.com/12138170/100330176-ea8fe780-2fce-11eb-9dea-0098f3f6a21a.png">
