### ISSUE TITLE
Brak odstępu od tytułu komponentu karty na stronie głównej 

### ISSUE THREAD

**Issue by Frezzu** [pspaczek/nowa-zhp#31]
1. Strona główna, obok "Aktualności"
2. Tytuł komponetu "STREFA instruktorska..."
3. Odstęp od dołu wydaje się zbyt mały
4. Błąd występuje na desktopie oraz telefonie z małym ekranem

![Screenshot 2020-11-26 at 00 08 40](https://user-images.githubusercontent.com/12649303/100290545-e9819a80-2f7b-11eb-90e4-886d73da2b79.png)
![Screenshot 2020-11-26 at 00 09 48](https://user-images.githubusercontent.com/12649303/100290548-eab2c780-2f7b-11eb-8145-533a6ea83c09.png)

**Comment by pspaczek** [comment]
## rozwiązane
<img width="423" alt="Zrzut ekranu 2020-11-26 o 09 54 01" src="https://user-images.githubusercontent.com/12138170/100328932-583b1400-2fcd-11eb-8d40-62b249619cf1.png">
<img width="1078" alt="Zrzut ekranu 2020-11-26 o 09 53 45" src="https://user-images.githubusercontent.com/12138170/100328912-55402380-2fcd-11eb-8e7f-e0d41ee4b72a.png">
