### ISSUE TITLE
Różne odstępy od góry tytułów "POZNAJ NAS" i "CHCESZ ZAPISAĆ SWOJE...."

### ISSUE THREAD

**Issue by Frezzu** [pspaczek/nowa-zhp#32]
1. Wersja mobilna, strona główna, komponent "POZNAJ NAS"
2. Odstęp od góry napis "POZNAJ NAS" jest inny niż ten w komponencie pod nim.
3. + Zielona nakładka na obrazka "POZNAJ NAS" wydaje się przesunięta.

![Screenshot 2020-11-26 at 00 20 49](https://user-images.githubusercontent.com/12649303/100291191-619c9000-2f7d-11eb-8a91-70628e73d871.png)
![127227994_1703147843193029_4917758310364761606_n](https://user-images.githubusercontent.com/12649303/100290918-b986c700-2f7c-11eb-83c2-324fac1ecad6.jpg)

**Comment by pspaczek** [comment]
## rozwiązano
<img width="341" alt="Zrzut ekranu 2020-11-26 o 10 02 57" src="https://user-images.githubusercontent.com/12138170/100329921-9553d600-2fce-11eb-994a-e27625ddda28.png">
<img width="1239" alt="Zrzut ekranu 2020-11-26 o 10 03 28" src="https://user-images.githubusercontent.com/12138170/100329968-a6044c00-2fce-11eb-93d4-0be5302f49bf.png">
