### ISSUE TITLE
na stronie symbole ZHP nic nie ma

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#33]
może warto ją usunąć skoro do symboli da się przejść z innych stron?
https://spaczek.dev/symbole/

**Comment by pspaczek** [comment]
Martyna, jak robicie strony typu https://spaczek.dev/strefa-instruktorska to musicie zaktualizować linki do nich w menu

**Comment by arturlamali** [comment]
Właśnie, a czy to nie jest tak, że przekierowanie nie działa? Przekierowanie z spaczek.dev/strefa-instruktorska na strony.zhp.pl/strefa-instruktorska jest ustawione w edytorze tej strony.
