### ISSUE TITLE
czarne obramowanie zaznaczonych elementów

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#34]
![image](https://user-images.githubusercontent.com/36226444/100331779-e06ee880-2fd0-11eb-9d2c-d4c2f8ecbfce.png)

domyślam się że to kwestia przeglądarki, bo na Chrome je widać, na Firefox go nie ma

**Comment by pspaczek** [comment]
accessybility, powinno być widoczne
