### ISSUE TITLE
formularz kategorii - odznaczanie i zaznaczanie

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#36]
czy te (x) jest faktycznie potrzebny przy zaznaczonych kategoriach? ja bym go usunął, to raczej dość intuicyjne że jak klikniemy w zaznaczoną (zieloną) kategorię to się ona odznaczy
![image](https://user-images.githubusercontent.com/36226444/100332122-4ce9e780-2fd1-11eb-9df5-bb7d10240101.png)

**Comment by pspaczek** [comment]
Jest:
![Zrzut ekranu 2021-01-20 o 14 23 31](https://user-images.githubusercontent.com/12138170/105180624-1b9e1b80-5b2b-11eb-8c95-3bd383ff4b88.png)
