### ISSUE TITLE
Server error po wejściu na stronę z wyszukiwarki

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#4]
# kroki
1. Wpisz w wyszukiwarkę _harc_ i kliknij enter
1. z listy wyników kliknij _Krzyrz harcerski_

# oczekiwany rezultat
Otwiera się strona https://spaczek.dev/odkryj/krzyz-harcerski

# osiągnięty rezultat
Otwiera się strona https://spaczek.dev/krzyz-harcerski i wyświetla błąd servera

**Comment by pspaczek** [comment]
## powód błędu
brak slugu rodzica w URL'u powinno być /odkryj/krzyż-harcerski

**Comment by pspaczek** [comment]
naprawione https://spaczek.dev/szukaj?search=harc
