### ISSUE TITLE
sekcja partnerzy na stronie głównej jest pusta

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#40]
![image](https://user-images.githubusercontent.com/36226444/100332883-3abc7900-2fd2-11eb-820a-237a44a9d6da.png)

**Comment by szczot3k** [comment]
Może nie pusta - miałem już zgłaszać błędnego instagrama, ale ładuje się DŁUGOOOOOOOOO (like, cmon, strasznie długo)
![image](https://user-images.githubusercontent.com/23485507/100339737-8a9f3e00-2fda-11eb-98d8-ae9038a3ce5a.png)

**Comment by szczot3k** [comment]
![image](https://user-images.githubusercontent.com/23485507/100340005-dc47c880-2fda-11eb-9965-7593172210ad.png)
Waterfall przy ładowaniu treści z dołu (instagrama, facebooka i partnerów) - 18sekund to strasznie długo.

**Comment by pspaczek** [comment]
problem występował dla firefox
![Uploading Zrzut ekranu 2020-11-26 o 13.03.06.png…]()
