### ISSUE TITLE
Potwierdzam występuje:  nowe.zhp.pl/

### ISSUE THREAD

**Issue by dkoryto** [pspaczek/nowa-zhp#41]
Potwierdzam występuje:  nowe.zhp.pl/

Attaching to nowa-zhp_web_1
web_1  | yarn run v1.22.5
web_1  | $ cd packages/app && yarn start
web_1  | $ nuxt start
web_1  | ✔ Sentry reporting is enabled (client side: enabled, server side: enabled)
web_1  | ℹ Listening on: http://172.18.0.2:3000/
web_1  | 
web_1  |  ERROR  Request failed with status code 403
web_1  | 
web_1  |   at createError (/usr/src/nuxt-app/node_modules/axios/lib/core/createError.js:16:15)
web_1  |   at settle (/usr/src/nuxt-app/node_modules/axios/lib/core/settle.js:17:12)
web_1  |   at IncomingMessage.handleStreamEnd (/usr/src/nuxt-app/node_modules/axios/lib/adapters/http.js:244:11)
web_1  |   at IncomingMessage.emit (events.js:327:22)
web_1  |   at IncomingMessage.EventEmitter.emit (domain.js:548:15)
web_1  |   at endReadableNT (_stream_readable.js:1327:12)
web_1  |   at processTicksAndRejections (internal/process/task_queues.js:80:21)
web_1  |

_Originally posted by @dkoryto in https://github.com/pspaczek/nowa-zhp/issues/29#issuecomment-734290612_

**Comment by pspaczek** [comment]
## rozwiązanie
https://github.com/pspaczek/nowa-zhp/commit/19cec821873d5b99c28c44acac45d38c61d962ff 
problem występował tylko na serwerze

**Comment by pspaczek** [comment]
## rozwiązane
prod.przemyslawspaczek.pl odrzucał połączenie od serwera ZHP (403), przeniesiono WordPress na serwer ZHP
