### ISSUE TITLE
Powtórka - #7

### ISSUE THREAD

**Issue by szczot3k** [pspaczek/nowa-zhp#42]
na zhp.pl/wracamy nie ma aktualnie nic

**Comment by marti-xd** [comment]
Już jest :D

**Comment by szczot3k** [comment]
![image](https://user-images.githubusercontent.com/23485507/100739256-1a782a00-33d7-11eb-8121-813680031856.png)
Wciąż nie.

**Comment by pspaczek** [comment]
## rozwiązane
https://github.com/pspaczek/nowa-zhp/commit/453c76d3fa50d502fa413dc163bd0e147f8916f9 posts
https://github.com/pspaczek/nowa-zhp/commit/5be134b580d317b1e2a54c26981a9311d32c073e pages
