### ISSUE TITLE
brak linkowania kafli wpisów na zhp.pl/aktualnosci

### ISSUE THREAD

**Issue by arturlamali** [pspaczek/nowa-zhp#43]
https://zhp.pl/aktualnosci - kafle są zalinkowane nie do wpisów, a do https://zhp.pl/aktualnosci

**Comment by arturlamali** [comment]
![obraz](https://user-images.githubusercontent.com/74903042/100783525-2f23e480-340e-11eb-9670-4ca0328c7329.png)

**Comment by pspaczek** [comment]
## rozwiązane

![Zrzut ekranu 2020-12-2 o 08 08 23](https://user-images.githubusercontent.com/12138170/100840039-92952d00-3475-11eb-8a3a-5f2d93e5aedb.png)
