### ISSUE TITLE
401 - archiwum

### ISSUE THREAD

**Issue by arturlamali** [pspaczek/nowa-zhp#44]
Na stronie przykładowej: https://zhp.pl/instrumenty-metodyczne/metodyka-wedrownicza

Po kliknięciu na dowolny link załącznika, przekierowuje nas do https://archiwum.zhp.pl/wp-content/uploads/2020/02/Karta-proby-Harcerki-Orlej_03.02.pdf

Ta strona z kolei prosi o zalogowanie do strony archiwum.zhp.pl.

**Comment by pspaczek** [comment]
## rozwiązane
pliki powinny być pobierane z instancji work.zhp.pl
pliki z paźdzernik / lilstopad 2020 nie zostały przenione, zostaną uzupełnione w nocy ze strony zhp.pl
