### ISSUE TITLE
Kafelki wyszukiwanych treści 

### ISSUE THREAD

**Issue by LaszczykM** [pspaczek/nowa-zhp#45]
![Uploading Screenshot_20201201-204954.png…]()
Brak dopasowania kafelków wyszukiwanych treści w wersji mobilnej.

**Comment by pspaczek** [comment]
Było
<img width="594" alt="Zrzut ekranu 2021-01-20 o 12 31 13" src="https://user-images.githubusercontent.com/12138170/105169145-644dd880-5b1b-11eb-8680-f97dd014309d.png">

Jests
<img width="1439" alt="Zrzut ekranu 2021-01-20 o 12 41 59" src="https://user-images.githubusercontent.com/12138170/105170209-e4287280-5b1c-11eb-8c5b-757128184eb5.png">
