### ISSUE TITLE
mogą cię także zainteresować - multiplikacja proponowanych treści

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#47]
![image](https://user-images.githubusercontent.com/36226444/101183737-31758100-3650-11eb-8632-c7042317a51e.png)

**Comment by szczot3k** [comment]
@janekk97, zwyczajnie KPP może Cię POTĘŻNIE zainteresować

**Comment by janekk97** [comment]
XD

**Comment by pspaczek** [comment]
brak informacji o podstronie, w przypadku jeżeli błąd nadal występuje proszę o adres podstrony
