### ISSUE TITLE
Slider wydarzeń 

### ISSUE THREAD

**Issue by arturlamali** [pspaczek/nowa-zhp#49]
Na liderze wydarzeń na stronie głównej wyświetlana jest tylko określona ilość ostatnio opublikowanych wydarzeń, nie wszystkich.

**Comment by pspaczek** [comment]
@arturlamali @marti-xd wyświetlanie nieograniczonej liczby wydarzeń jest bez sensu spowalnia to stronę a i tak nikt ich nie przeczyta... być może lepszą opcją jest 'zobacz wszystkie',

**Comment by marti-xd** [comment]
A da się zrobić żebyśmy to my klikali jakie mają być?
Plus dodałaby "Zobacz wszystkie!"

**Comment by pspaczek** [comment]
@marti-xd tak, to tak zrobię

**Comment by pspaczek** [comment]
![Zrzut ekranu 2021-01-23 o 09 43 49](https://user-images.githubusercontent.com/12138170/105573741-fe05c780-5d5f-11eb-8d47-4a2188b7304f.png)
Strona Główna -> Kategoria wydarzeń
id kategori - wyświetli max 25 wydarzeń z kategorii (w kategori musi być min 4 wpisy), teraz jest 440 Wyróżnione
puste pole - max 25 wydarzeń
![Zrzut ekranu 2021-01-23 o 09 46 42](https://user-images.githubusercontent.com/12138170/105573746-02ca7b80-5d60-11eb-9865-e6f2874eece0.png)

**Comment by arturlamali** [comment]
Działa
