### ISSUE TITLE
Link Strategia ZHP 2025 nie działa

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#5]
# Kroki
1. wejdź na stronę główną
1. z menu _Odkryj ZHP_ -> _Zawsze pod ręką_ -> _Strategia ZHP 2025_ 

# Oczekiwany rezultat
Otworzy się strona np. https://spaczek.dev/strategia2025/wdrazanie-strategii-zhp2025 lub inna o strategii

# Otrzymany rezultat
strona https://spaczek.dev/strategia2025/wdrazanie-strategii-zhp2025 się otwiera ale pojawia się błąd _This page could not be found_

Co ciekawe po odświeżeniu działa

![image](https://user-images.githubusercontent.com/865361/99950722-42cfab00-2d7d-11eb-8032-37c6972d1085.png)
Przeglądarka: Firefox, wyłączony adblock

**Comment by qj0n** [comment]
To samo się dzieje pod linkiem Instytucja Certyfikująca ZHP - strona błędu, ale po refreshu wchodzi

**Comment by pspaczek** [comment]
Pod spodem jest redirect "JS'owy" był z nim problem ale już ryra #6
