### ISSUE TITLE
Brak wyróżnień graficznych Nagłówków

### ISSUE THREAD

**Issue by arturlamali** [pspaczek/nowa-zhp#50]
Nagłówki nie są wyróżnione pod względem wielkości.

**Comment by pspaczek** [comment]
Desktop:
![Zrzut ekranu 2021-01-20 o 15 00 16](https://user-images.githubusercontent.com/12138170/105184944-3de66800-5b30-11eb-955c-616f7f279393.png)

Mobile:
![Zrzut ekranu 2021-01-20 o 14 59 37](https://user-images.githubusercontent.com/12138170/105184959-4179ef00-5b30-11eb-8e6a-3065323d3e34.png)

**Comment by arturlamali** [comment]
Nie działa.
