### ISSUE TITLE
Podgląd newsów

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#53]
Nie działa podgląd newsów

**Comment by pspaczek** [comment]
@marti-xd tego taska nie rozumiem

**Comment by marti-xd** [comment]
Jak dodajesz newsa to zazwyczaj mogliśmy zrobić "Zobacz" a teraz nie działa :(

**Comment by pspaczek** [comment]
k, już wyłapałem o czym mowa 🦄

**Comment by pspaczek** [comment]
Dodałem do docs, na przyszłość wystarczy tylko podmiana URL'a tutaj 🦄 
<img width="1272" alt="Zrzut ekranu 2021-01-21 o 17 03 09" src="https://user-images.githubusercontent.com/12138170/105376903-8a9e7180-5c0a-11eb-9648-8aad6fcee0d8.png">

**Comment by pspaczek** [comment]
powyższe rozwiązanie psuje WordPress, zmiany trzeba dokonać w `htaccess`

**Comment by pspaczek** [comment]
Dodałem do ustawień motywu nową opcję. Jeżeli WordPress i WWW są na różnych URL'ach to trzeba podać tu adres WWW. Ustawiłem na zhp.pl powinno działać przekierowanie z work.zhp.pl

![Zrzut ekranu 2021-01-31 o 10 59 31](https://user-images.githubusercontent.com/12138170/106380787-d55f7c80-63b4-11eb-9a04-4c87c1591b22.png)

**Comment by arturlamali** [comment]
Działa, super!
