### ISSUE TITLE
Wersja mobilna: nie mieszczą się kafelki newsów i wydarzeń (tnie)

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#56]

**Comment by pspaczek** [comment]
Desktop/RWD:
![Zrzut ekranu 2021-01-20 o 16 18 19](https://user-images.githubusercontent.com/12138170/105195739-36788c00-5b3b-11eb-9efe-e2386a380038.png)
![Zrzut ekranu 2021-01-20 o 16 18 26](https://user-images.githubusercontent.com/12138170/105195733-34aec880-5b3b-11eb-8e2b-aeadf9e3f9ef.png)
Mobile: 
![Zrzut ekranu 2021-01-20 o 16 12 08](https://user-images.githubusercontent.com/12138170/105194895-4d6aae80-5b3a-11eb-8386-dfe2d8ef5d51.png)
![Zrzut ekranu 2021-01-20 o 16 12 20](https://user-images.githubusercontent.com/12138170/105194898-4e9bdb80-5b3a-11eb-99e3-f69932218904.png)
Dopasowanie do designu:
![Zrzut ekranu 2021-01-20 o 16 18 51](https://user-images.githubusercontent.com/12138170/105195834-4e501000-5b3b-11eb-8faf-4131c36f3cae.png)
![Zrzut ekranu 2021-01-20 o 16 18 44](https://user-images.githubusercontent.com/12138170/105195840-4f813d00-5b3b-11eb-83a1-454fc3633c84.png)
