### ISSUE TITLE
Wersja mobilna: za duże logo WOSM i WAGGGS

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#57]

**Comment by pspaczek** [comment]
Było:
![Zrzut ekranu 2021-01-20 o 22 07 09](https://user-images.githubusercontent.com/12138170/105234688-e7971a80-5b6b-11eb-9234-6f710bc64177.png)

Jest:
![Zrzut ekranu 2021-01-20 o 22 07 27](https://user-images.githubusercontent.com/12138170/105234711-eebe2880-5b6b-11eb-8e3b-821acb7d8922.png)
