### ISSUE TITLE
Cytat w wersji mobilnej

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#59]
Wersja mobilna: cytat we wpisie nie mieści się w obszarze okna Wersja desktop: cytat dzieli się na kolumny - chcemy jedną kolumnę

**Comment by pspaczek** [comment]
Jest:
![Zrzut ekranu 2021-01-20 o 15 26 09](https://user-images.githubusercontent.com/12138170/105188114-d7634900-5b33-11eb-85cb-ef12475049b2.png)
