### ISSUE TITLE
Strona z błędem 404 wyświetla "Czy wiesz, że..."

### ISSUE THREAD

**Issue by szczot3k** [pspaczek/nowa-zhp#6]
![image](https://user-images.githubusercontent.com/23485507/99951358-49aaed80-2d7e-11eb-92a9-fcce17e75c0c.png)

Strona "This page could not be found" wciąż wyświetla ciekawostki z "Czy wiesz, że". Dobrze byłoby, żeby tego nie wyświetlała, a w tym miejscu pojawił się np. odnośnik do strony głównej

**Comment by szczot3k** [comment]
Albo jeżeli wciąż ma wyświetlać - to w widoczny sposób.

**Comment by pspaczek** [comment]
Problem występuje np. tu https://spaczek.dev/kapitula/aktualnosci

**Comment by pspaczek** [comment]
naprawione
Odkryj ZHP / Kapituła Krzyża „Za Zasługi dla ZHP” i „Medalu Wdzięczności ZHP” było tego przykładzem, teraz powinno być ok
