### ISSUE TITLE
Automatyczne wyszarzanie wydarzenia po zakończeniu

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#61]

**Comment by pspaczek** [comment]
Nie powinniście usuwać minionych wydarzeń. Na liście wydarzeń po zakończeniu
- z eventu znika data
- zostaje wyszarzony
![Zrzut ekranu 2021-01-23 o 12 30 32](https://user-images.githubusercontent.com/12138170/105576971-ee45ad80-5d76-11eb-8394-5c66fdd1efb5.png)

we wpisie bez zmian
![Zrzut ekranu 2021-01-23 o 12 32 35](https://user-images.githubusercontent.com/12138170/105577004-1503e400-5d77-11eb-8520-3ea754125568.png)
