### ISSUE TITLE
Dodawanie wydarzeń przez gości, akceptacja z maila promocja@zhp.pl

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#62]

**Comment by pspaczek** [comment]
Dopisałem moduł wydarzeń. Żeby wszystko działało musicie ustawić domeny z których można weryfikować wydarzenia, tytył maila i treść maila jaki zostanie wysłany w celu potwierdzenia zgłoszenia. 

![Zrzut ekranu 2021-02-8 o 14 19 46](https://user-images.githubusercontent.com/12138170/107225126-b72ef780-6a18-11eb-9f91-8b9544a2beb3.png)
