### ISSUE TITLE
Kalendarz w wydarzeniach

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#63]
Notatka Przemka: data wydarzenia z ACF, dodać WP QUERY które do API

**Comment by pspaczek** [comment]
+ wydarzenia są sortowane od tych które zaczynają się najpóźniej, pewnie tu będzie pole do jakiś poprawek
<img width="377" alt="Zrzut ekranu 2021-01-25 o 20 16 18" src="https://user-images.githubusercontent.com/12138170/105754326-34069f80-5f4a-11eb-8753-1851808d67ba.png">
