### ISSUE TITLE
Kontrolki w filtrach sortowane alfabetycznie

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#64]
Notatka Przemka: pozbyć się mapowania na obiekt, obiekt nie zachowuje kolejności

**Comment by pspaczek** [comment]
![Zrzut ekranu 2021-01-23 o 11 55 52](https://user-images.githubusercontent.com/12138170/105576303-2696bd00-5d72-11eb-98a1-160cc87f1065.png)
![Zrzut ekranu 2021-01-23 o 11 56 02](https://user-images.githubusercontent.com/12138170/105576305-27c7ea00-5d72-11eb-9727-8b8b2b8ee737.png)
