### ISSUE TITLE
Multiselect typ wydarzenia, metodyka na stronie /wydarzenia

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#65]

**Comment by pspaczek** [comment]
Na razie używam prostych pól select multiple
<img width="279" alt="Zrzut ekranu 2021-01-25 o 20 34 28" src="https://user-images.githubusercontent.com/12138170/105756318-babc7c00-5f4c-11eb-90ac-1ba7195dc21f.png">

**Comment by pspaczek** [comment]
![Zrzut ekranu 2021-01-28 o 20 38 39](https://user-images.githubusercontent.com/12138170/106189761-ffdcea00-61a8-11eb-85df-62278c001210.png)
