### ISSUE TITLE
style dla żałoba ZHP.pl

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#67]

**Comment by pspaczek** [comment]
Jest:
<img width="1430" alt="Zrzut ekranu 2021-01-20 o 21 54 59" src="https://user-images.githubusercontent.com/12138170/105233501-380d7880-5b6a-11eb-9cdc-e01d03589a00.png">

W zakładce Dostosowanie dodano Ustawiania motywu / Żałoba.
 
![Zrzut ekranu 2021-01-20 o 21 54 40](https://user-images.githubusercontent.com/12138170/105233495-36dc4b80-5b6a-11eb-8ada-c064e5e3298a.png)
![Zrzut ekranu 2021-01-20 o 21 54 47](https://user-images.githubusercontent.com/12138170/105233499-3774e200-5b6a-11eb-953c-8dcee6a67567.png)
