### ISSUE TITLE
działające osadzanie linków jako miniatur/gutenberg

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#68]
Przemek: dla dużych jak YouTube etc. działa ponieważ korzystaja z oEmbed bez tego nie jesteś w stanie pobrać miniatury strony. Czy macie gdzieś przykład gdzie działa to o czym piszesz ARTUR?

Artur: '@Artur: chodzi o osadzanie adresów URL z źródeł innych niż inny WP lub YouTube - nie generuje się miniatura, sprawdź, wklejając link https://rzeszow.wyborcza.pl/rzeszow/7,34962,25793469,koronawirus-wolontariusze-pomoga-osobom-starszym-i-potrzebujacym.html do wpisu

**Comment by pspaczek** [comment]
@marti-xd @arturlamali TL;TR nie ma takiej opcji tak jak napisałem, [wspierane portale](https://wordpress.org/support/article/embeds/)

tutaj wyjaśnienie tego od WordPress, https://wordpress.org/support/article/embeds/ po prostu nie jesteś w stanie pobrać takich danych ze strony. Dlatego też jeżeli do strony nie dodasz Facebooka to linkując posty z strony na FB będziesz dostawał shitowe miniatury
