### ISSUE TITLE
Iframe starej strony na https://spaczek.dev/wracamy/

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#7]
Pod adresem https://spaczek.dev/wracamy/ można znaleźć iframe do starej strony ZHP. Obecnie to działa ok, ale jeśli nowa strona zhp będzie zahostowana pod adresem zhp.pl to podejrzewam, że będzie cykliczne wstawianie iframe

**Comment by pspaczek** [comment]
Powstanie instancja dla landing pages budowanych w elementorze poza adresem zhp.pl
Wydział komunikacji obecnie użwa tego narzędzia do budowy "efektownych" stron.

**Comment by pspaczek** [comment]
## rozwiązanie
zamiast iframe użyte zostaną przekierowania na konkretne lending page
