### ISSUE TITLE
Przewijanie aktualności myszką / dodanie strzałek

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#70]
'@Olga "bo próbowałam albo klikać na to ucięte albo najeżdżać by samo się przesunęło albo cos klikać nad tym" Artur: tak, jak rozmawialiśmy przez telefon - dodajemy strzałki pod/nad

**Comment by pspaczek** [comment]
Dodano strzałki do karuzeli

![Zrzut ekranu 2021-02-3 o 19 38 21](https://user-images.githubusercontent.com/12138170/106793381-ae74a500-6657-11eb-901f-b24cc914e681.png)

**Comment by arturlamali** [comment]
Działa, super!
