### ISSUE TITLE
Dodanie wyszukiwarki w newsy (szukanie tylko w newsach)

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#72]
Przemek:
@Martyna @Artur jeżeli ma to zostać dodane to trzeba to przeprojektować. może warto dodać ikonę szukaj i dać dostęp do wyszukiwania z każdego miejsca na stronie | 

Artur: spoko, myślę, że możemy zrobić z wyszukiwaniem, ale fajnie, żeby to było większe, niż sama lupka

**Comment by pspaczek** [comment]
Nie mam pomysłu gdzie to wrzucić. Jeżeli macie jakiś pomysł na globalną szukajkę. Może chcecie coś zamienić stronami na belce. Na razie zrobiłem tak.
<img width="1398" alt="Zrzut ekranu 2021-01-21 o 19 48 49" src="https://user-images.githubusercontent.com/12138170/105397709-afeaaa00-5c21-11eb-8716-7885cb312ee3.png">

**Comment by pspaczek** [comment]
update:
<img width="1386" alt="Zrzut ekranu 2021-01-21 o 20 00 32" src="https://user-images.githubusercontent.com/12138170/105399020-54212080-5c23-11eb-9fd8-97da7bfa4f69.png">

**Comment by arturlamali** [comment]
Tylko to chodziło o zhp.pl/aktualnosci 😅
<img width="1427" alt="obraz" src="https://user-images.githubusercontent.com/74903042/105497347-ff32e800-5cbe-11eb-99fa-537f8229fa29.png">

Mogłoby być np. pod lub nad filtrami, styl taki jak wyszukiwarka z głównej.

**Comment by pspaczek** [comment]
![Zrzut ekranu 2021-01-23 o 08 51 28](https://user-images.githubusercontent.com/12138170/105572569-330e1c00-5d58-11eb-92c8-b2e1d270fb2a.png)
---
Przemek:
@martyna @artur jeżeli ma to zostać dodane to trzeba to przeprojektować. **_może warto dodać ikonę szukaj i dać dostęp do wyszukiwania z każdego miejsca na stronie_** |

Artur: spoko, myślę, że możemy zrobić z wyszukiwaniem, ale fajnie, żeby to było większe, niż sama lupka

**Comment by pspaczek** [comment]
![Zrzut ekranu 2021-01-23 o 21 07 12](https://user-images.githubusercontent.com/12138170/105612866-0e00c400-5dbf-11eb-95aa-dcbe747caebf.png)

Wiedziałem że z czymś będzie problem @arturlamali @marti-xd w obecnym układzie search tam średnio pasuje... trochę poprawi sytuacja jeżeli przeniesiemy go nad filtry i button bedzie obok zamiast pod search. 

na szybko było by mniej więcej tak...
![Zrzut ekranu 2021-01-23 o 21 11 49](https://user-images.githubusercontent.com/12138170/105612942-a5661700-5dbf-11eb-9089-a18c5816e8f1.png)

**Comment by arturlamali** [comment]
A jeśli załączone filtry przenieść nad wybór filtrów albo obok?

**Comment by arturlamali** [comment]
Jest super, można wdrażać!

**Comment by arturlamali** [comment]
<img width="1411" alt="obraz" src="https://user-images.githubusercontent.com/74903042/107239920-40e2c300-6a21-11eb-82f4-5008806746a3.png">

Super, tylko czy napis Czego dzisiaj chcesz dowiedzieć się o ZHP? Powininen wyświetlać się bardziej na środku?
