### ISSUE TITLE
kafelek nie przenosi do strony

### ISSUE THREAD

**Issue by janekk97** [pspaczek/nowa-zhp#74]
![image](https://user-images.githubusercontent.com/36226444/105014223-7575e700-5a40-11eb-8471-01b9297f7999.png)

**Comment by pspaczek** [comment]
@arturlamali @marti-xd do czego to podlinkować

**Comment by arturlamali** [comment]
Martyna, może zrobimy stronę zhp.pl/organizacja, tak jak w menu i damy tam wszystkie podstrony z tego menu? Chwilowo nie mogę tego zrobić, bo pokazuje mi błąd: Nie powiodła się publikacja. Prawdopodobnie jesteś offline.

**Comment by marti-xd** [comment]
Takk - tak jak zhp.pl/dotacje 

i dajmy tam statut, wszystkie władze

**Comment by pspaczek** [comment]
/dotacje to jeszcze hack, zakodowany z palca
@arturlamali podrzuć tytuły kafelków, obrazki i linki do nich ta strona nie powinna być w WordPress

**Comment by arturlamali** [comment]
No dobra, chyba, że zalinkujemy do zhp.pl/organizacja/statut-zhp po prostu?
Inne podstrony podobne są też podpięte pod to.

**Comment by arturlamali** [comment]
Czyli można linkować do zhp.pl/organizacja/statut-zhp ze spokojem.

**Comment by marti-xd** [comment]
Popieram

**Comment by pspaczek** [comment]
kafelek kieruje na wskazany przez @arturlamali link
