### ISSUE TITLE
Strony-błąd: Nie powiodła się publikacja. Prawdopodobnie jesteś offline.

### ISSUE THREAD

**Issue by arturlamali** [pspaczek/nowa-zhp#77]
<img width="1436" alt="obraz" src="https://user-images.githubusercontent.com/74903042/105496060-44561a80-5cbd-11eb-85f8-56c650375dd2.png">

Przy próbie opublikowania nowej strony pokazuje się powyższy błąd.

**Comment by pspaczek** [comment]
powiązane z #53 naprawienie tego błędu powoduje problemy z publikacją, przywrócono możliwość publikacji
