### ISSUE TITLE
Problem z partnerami

### ISSUE THREAD

**Issue by arturlamali** [pspaczek/nowa-zhp#78]
Po zmianie obrazka wyróżnionego partnerów z Obszar-roboczy-32.png na ZHP_partner-20.png wywala stronę.

**Comment by pspaczek** [comment]
Rekomenduję używać nazw bez `_` i `-` pozwoli to uniknąć wielu problemów, jeżeli jednak te nazwy są ważne to @arturlamali podeślij info o partnerze i pliki do podmiany.

**Comment by arturlamali** [comment]
Dobra, wszystko jasne!
