### ISSUE TITLE
Link STREFA | Instruktorska prowadzi do '#'

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#8]
1. wejdź na stronę główną
1. z menu Odkryj ZHP -> Zawsze pod ręką -> STREFA | Instruktorska 

# oczekiwane zachowanie
otworzy się jakaś strona na ten temat

# otrzymane zachowanie
przeładowuje się bieżąca strona i dodawany jest '#' do adresu

**Comment by pspaczek** [comment]
naprawione, kieruje na /strefa-instruktorska, treść podstrony do opracowania przez ZHP
