### ISSUE TITLE
Nakładanie sidebaru na content

### ISSUE THREAD

**Issue by msmaciek** [pspaczek/nowa-zhp#80]
Na stronie https://zhp.pl/odkryj/skladki/ sidebar nakłada się na content.
![Składki - Związek Harcerstwa Polskiego - zhp pl](https://user-images.githubusercontent.com/25992575/106393928-1c239580-63fa-11eb-81a0-c5aaf826288a.png)

**Comment by arturlamali** [comment]
Bez zmian - nie działa

**Comment by pspaczek** [comment]
Przeniesiono https://github.com/itwzhp/zhp-pl/issues/4
