### ISSUE TITLE
Strona organizacja

### ISSUE THREAD

**Issue by marti-xd** [pspaczek/nowa-zhp#81]
Zrobiona tak jak dotacje

WAŻNE
nie zmieniamy adresu tych stron

robimy zhp.pl/organizacja 

I nam na zielonych kwadratach dajemy:
Naczelniczka ZHP
Główna Kwatera ZHP
Przewodniczący ZHP
Rada Naczelna ZHP
Centralna Komisja Rewizyjna ZHP
Naczelny Sąd Harcerski ZHP
Statut ZHP

**Comment by pspaczek** [comment]
![Zrzut ekranu 2021-02-3 o 20 40 20](https://user-images.githubusercontent.com/12138170/106799879-10390d00-6660-11eb-9436-937b4bac19ee.png)

**Comment by arturlamali** [comment]
Naczelny Sąd Harcerski ZHP - z wielkich liter

**Comment by pspaczek** [comment]
Poprawione http://develop.przemyslawspaczek.pl/organizacja/
