### ISSUE TITLE
Nie aktualny link w poście

### ISSUE THREAD

**Issue by msmaciek** [pspaczek/nowa-zhp#82]
W [poście](https://zhp.pl/2020/wysylka-do-pilotazu-reformy-sim/) nie działa link kierujący do hubu informacyjnego GK ZHP.

**Comment by szczot3k** [comment]
Za sam content odpowiada WKiP, afaik tutaj zgłaszane powinny być błędny z samym działaniem strony.  Najlepiej podesłac info na promocja@zhp.pl

**Comment by msmaciek** [comment]
Jasne, przepraszam za zamieszanie. :)
