### ISSUE TITLE
Linki do plików prowadzą do localhost

### ISSUE THREAD

**Issue by qj0n** [pspaczek/nowa-zhp#9]
1. wejdź na https://spaczek.dev/sprawozdania/rok-2019
1. kliknij w pierwszy link do pliku 

# Oczekiwany rezultat
Otwiera się prawidłowy link do pliku LUB przekierowuje mnie na logowanie się do Sharpeointa, aby pobrać plik (jeśli plik jest dostępny tylko dla członków)

# otrzymany rezultat
Przekierowuje mnie na http://localhost:8888/wordpress/wp-content/uploads/2020/05/Sprawozdanie-GK-ZHP-2019-Czesc-A-Realizacja-uchwal-zjazdu.pdf

**Comment by pspaczek** [comment]
naprawiono przekierowania z localhost:8888/wordpress na prod.przemyslawspaczek.pl
